print("I saw a girl and I thought she was _________")
adjective1 = input("Please enter an adjective: ")
print("I saw a girl and I thought she was " + adjective1)
print("I went to talk to her but she was _________" + " and wanted to sleep")
adjective2 = input("Please enter an adjective: ")
print("I went to talk to her but she was " + adjective2 + " and wanted to sleep")
print("I was suprised because she looked _________"+ " but looks can be decieving")
adjective3 = input("Please enter an adjective: ")
print(" I was suprised because she looked " + adjective3 + " but looks can be decieving")
print("I said bye and went home and realized I was _________" + " too")
adjective4 = input("Please enter an adjective: ")
print("I said bye and went home and realized I was " + adjective4 + " too")
print("when I woke up, I was _________" + " but I was still _________" + " enough to go and look for her")
adjective5 = input("Please enter an adjective: ")
adjective6 = input("Please enter an adjective: ")
print("when I woke up, I was " + adjective5 + " but I was still " + adjective6 + " enough to go and look for her")
